  jwt:
    secretKey: mysupersecurekeyformysafarsaathijwt1234567890abcdefABCDEF1234567890


security:
    internal-gateway-secret:

server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

        routes:
          - id: auth-service
            uri: lb://auth-service
            predicates:
              - Path=/auth/**
            filters:
              - name: AuthenticationFilter

          - id: org-service
            uri: lb://org-service
            predicates:
              - Path=/org/**

            filters:
              - name: AuthenticationFilter




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
